version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres-bd
    ports:
      - "5432:5432"
    networks: [ 'mynetwork' ]

  jersey-jax-rs:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks: ['mynetwork']
networks: {mynetwork: {}}

